// Generated by Sharpy compiler
// DO NOT EDIT - Changes will be overwritten

using System;
using Sharpy;

namespace SharpyGenerated;

/// <summary>
/// Module-level functions and constants
/// </summary>
public static class __Module__
{
        public static void Main()
    {
        Sharpy.Exports.Print("Hello, World!");
        Sharpy.Exports.Print("This is Sharpy!");
        Sharpy.Exports.Print("Compiled to C# successfully!");
    }
}

