@startuml Sharpy

interface "Sharpy.IHashable"
interface "Sharpy.IEquatable"
interface "Sharpy.IEquatableWith<T>"
interface "Sharpy.IEquatable<T>"
interface "Sharpy.IIdentifiable"
interface "Sharpy.IBoolConvertible"
interface "Sharpy.IStrConvertible"
interface "Sharpy.IInequatable<T>"
interface "Sharpy.IInequatableWith<T>"
interface "Sharpy.IEquatable"
interface "Sharpy.IMutableSequence<S, T>"
interface "Sharpy.IMutableSequence<T>"
interface "Sharpy.ISequence<T>"

class "System.Object"
class "Sharpy.Object"
class "Sharpy.List<T>"

interface "System.IEquatable<T>"

"Sharpy.Object" --|> "System.Object"
"Sharpy.Object" ..|> "Sharpy.IEquatable<T>"
"Sharpy.Object" ..|> "Sharpy.IInequatable<T>"
"Sharpy.Object" ..|> "Sharpy.IIdentifiable"
"Sharpy.Object" ..|> "Sharpy.IStrConvertible"
"Sharpy.Object" ..|> "Sharpy.IBoolConvertible"
"Sharpy.List<T>" --|> "Sharpy.Object"
"Sharpy.List<T>" ..|> "Sharpy.IEquatable<T>"

"Sharpy.IEquatable<T>" --|> "Sharpy.IEquatableWith<T>"
"Sharpy.IInequatable<T>" --|> "Sharpy.IInequatableWith<T>"
"Sharpy.IInequatableWith<T>" --|> "Sharpy.IEquatableWith<T>"
"Sharpy.IEquatableWith<T>" --|> "Sharpy.IEquatable"
"Sharpy.IEquatableWith<T>" --|> "System.IEquatable<T>"
"Sharpy.IEquatable" --|> "Sharpy.IHashable"
@enduml
