// Generated by Sharpy compiler
// DO NOT EDIT - Changes will be overwritten

using System;
using Sharpy;

namespace SharpyGenerated;

/// <summary>
/// Module-level functions and constants
/// </summary>
public static class __Module__
{
        private static void Greet(object name)
    {
        Sharpy.Exports.Print("Hello,", name, "!");
    }
        // TODO: Name collision: 'greet' and '' both mangle to 'Greet'
}

