/// Main code generator for Sharpy → C#
///
/// This is the entry point for code generation. It takes a typed AST
/// (from semantic analysis) and produces C# source code.
///
/// # P0 (Minimum Viable) Features:
/// - Basic expressions (literals, binary ops, comparisons)
/// - Name mangling (`snake_case` → PascalCase/camelCase)
/// - Module structure (namespace + __Module__ class)
/// - Simple type mappings (int, str, bool, etc.)
///
/// # P1 (Next Phase) Features:
/// - Function definitions
/// - Class/struct/protocol definitions
/// - Control flow (if, for, while)
/// - Function calls
/// - Method calls with builtin resolution
use crate::ast::{Module, Node};
use crate::semantic::SymbolTable;

use super::context::CodeGenContext;
use super::{CodeGenError, CodeGenResult};

/// Main code generator
pub struct CodeGenerator {
    context: CodeGenContext,
}

impl CodeGenerator {
    /// Create a new code generator
    #[must_use]
    pub fn new(symbol_table: SymbolTable) -> Self {
        Self {
            context: CodeGenContext::new(symbol_table),
        }
    }

    /// Generate C# code from a Sharpy module
    ///
    /// # Arguments
    /// * `module` - The root AST module node
    ///
    /// # Returns
    /// Complete C# source code as a string
    ///
    /// # Errors
    /// Returns error if code generation fails
    pub fn generate(&mut self, module: &Module) -> CodeGenResult<String> {
        let mut output = String::new();

        // 1. File header comment
        output.push_str("// Generated by Sharpy compiler\n");
        output.push_str("// DO NOT EDIT - Changes will be overwritten\n\n");

        // 2. Using statements
        for using in self.context.get_using_statements() {
            output.push_str(using);
            output.push('\n');
        }
        output.push('\n');

        // 3. Namespace declaration
        let namespace = self.get_namespace_from_module(module)?;
        output.push_str(&format!("namespace {namespace};\n\n"));

        // 4. Module-level static class (__Module__)
        output.push_str("/// <summary>\n");
        output.push_str("/// Module-level functions and constants\n");
        output.push_str("/// </summary>\n");
        output.push_str("public static class __Module__\n");
        output.push_str("{\n");

        self.context.indent();

        // 5. Generate module body
        for stmt in &module.body {
            match self.generate_top_level_statement(stmt) {
                Ok(code) => {
                    if !code.is_empty() {
                        output.push_str(&self.context.get_indent());
                        output.push_str(&code);
                        output.push('\n');
                    }
                }
                Err(e) => {
                    // For P0, skip unimplemented features with a comment
                    output.push_str(&self.context.get_indent());
                    output.push_str(&format!("// TODO: {e}\n"));
                }
            }
        }

        self.context.dedent();

        output.push_str("}\n");

        Ok(output)
    }

    /// Get namespace from module (defaults to "`SharpyGenerated`")
    fn get_namespace_from_module(&self, _module: &Module) -> CodeGenResult<String> {
        // For P0, use a fixed namespace
        // In P1, derive from file path or module name
        Ok("SharpyGenerated".to_string())
    }

    /// Generate code for a top-level statement
    fn generate_top_level_statement(&mut self, stmt: &Node) -> CodeGenResult<String> {
        match stmt {
            // For P0, we only handle simple expressions as demonstration
            Node::Constant(_c) => {
                let expr_code = super::expression::generate_expression(stmt, &mut self.context)?;
                Ok(format!("// Constant: {expr_code}"))
            }
            _ => Err(CodeGenError::NotImplemented {
                feature: format!("Top-level statement: {stmt:?}"),
            }),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_basic_codegen_structure() {
        let symbol_table = SymbolTable::new();
        let mut generator = CodeGenerator::new(symbol_table);

        let module = Module {
            body: vec![],
            source: None,
        };

        let result = generator.generate(&module).unwrap();

        // Should have file header
        assert!(result.contains("// Generated by Sharpy compiler"));

        // Should have using statements
        assert!(result.contains("using System;"));
        assert!(result.contains("using Sharpy;"));

        // Should have namespace
        assert!(result.contains("namespace SharpyGenerated;"));

        // Should have __Module__ class
        assert!(result.contains("public static class __Module__"));
    }
}
