using System.Collections.Immutable;
using Sharpy.Compiler.Parser.Ast;

namespace Sharpy.Compiler.Analysis.ControlFlow;

/// <summary>
/// Describes how control flow leaves a basic block.
/// Every basic block (except exit) has exactly one terminator.
/// </summary>
/// <remarks>
/// Terminators are immutable records - they represent the computed control flow
/// and don't change after CFG construction.
/// </remarks>
public abstract record BlockTerminator
{
    /// <summary>
    /// The statement that caused this terminator (for diagnostics).
    /// </summary>
    public Statement? SourceStatement { get; init; }
}

/// <summary>
/// Unconditional branch to a single target block.
/// Generated by: fall-through, unconditional goto
/// </summary>
public sealed record BranchTerminator(BasicBlock Target) : BlockTerminator;

/// <summary>
/// Conditional branch based on a boolean expression.
/// Generated by: if statements, while conditions, for conditions
/// </summary>
public sealed record ConditionalBranchTerminator(
    Expression Condition,
    BasicBlock TrueTarget,
    BasicBlock FalseTarget
) : BlockTerminator;

/// <summary>
/// Multi-way branch based on a value.
/// Generated by: match/switch statements (v0.2.x)
/// </summary>
public sealed record SwitchTerminator(
    Expression Value,
    ImmutableArray<SwitchCase> Cases,
    BasicBlock? DefaultTarget
) : BlockTerminator;

/// <summary>
/// A single case in a switch terminator.
/// </summary>
public sealed record SwitchCase(
    Pattern? Pattern, // null for default case
    Expression? Guard,
    BasicBlock Target
);

/// <summary>
/// Return from the function.
/// Generated by: return statements
/// </summary>
public sealed record ReturnTerminator(Expression? Value) : BlockTerminator;

/// <summary>
/// Throw an exception.
/// Generated by: raise statements (re-raise has null Exception)
/// </summary>
public sealed record ThrowTerminator(Expression? Exception) : BlockTerminator;

/// <summary>
/// Break out of a loop to a specific target.
/// Generated by: break statements and BreakWithFlagStatement (internal)
/// </summary>
/// <remarks>
/// For BreakWithFlagStatement (used for loop-else), the flag assignment
/// is added as a statement before this terminator is reached.
/// </remarks>
public sealed record BreakTerminator(BasicBlock Target) : BlockTerminator;

/// <summary>
/// Continue to the next iteration of a loop.
/// Generated by: continue statements
/// </summary>
public sealed record ContinueTerminator(BasicBlock Target) : BlockTerminator;

/// <summary>
/// Re-raise the current exception (bare 'raise' with no expression).
/// Can only appear inside an except handler.
/// </summary>
public sealed record RethrowTerminator() : BlockTerminator;

/// <summary>
/// Marker terminator for blocks that don't naturally terminate (unreachable).
/// This should not appear in a well-formed CFG.
/// </summary>
public sealed record UnreachableTerminator() : BlockTerminator;
