using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text.Json;
using System.Text.RegularExpressions;
using FluentAssertions;
using Sharpy.Compiler.Diagnostics;
using Sharpy.Compiler.Semantic;
using Sharpy.Compiler.Semantic.Registry;
using Xunit;
using Xunit.Abstractions;

namespace Sharpy.Compiler.Tests.Conformance;

/// <summary>
/// Conformance sweep for the contract: <b>one runtime type has one surface, however the type system
/// arrived at it.</b> A value can reach the checker two ways — a TYPE ANNOTATION resolved by
/// <c>TypeResolver</c> (<c>x: DictKeyView[str, int] = d.keys()</c>) or an EXPRESSION typed from
/// discovery/bridge metadata (<c>d.keys()</c> used inline). Those are different producers of the
/// same <c>GenericType</c>, and everything downstream — operator resolution, protocol dispatch —
/// must not be able to tell them apart.
///
/// <para>It could. #1496: <c>x | y</c> on an annotation-typed <c>DictKeyView</c> was ACCEPTED and
/// threw <c>NotSupportedException</c> at runtime, while the inline <c>d.keys() | e.keys()</c>
/// spelling of the same operation was REFUSED (SPY0222) — the two paths were wrong in opposite
/// directions at once, so neither could be found by testing the other. The cause was one field:
/// the annotation path stamps <c>GenericType.GenericDefinition</c> and the discovery path stamps
/// <c>ClrOriginTypeName</c>, and <c>TryConstructClosedGeneric</c> read only the first. #1497 was the
/// same shape in protocol recognition. Both were found by hand, one spelling at a time. This sweep
/// writes both spellings of every reachable type, on purpose.</para>
///
/// <para><b>Why the type list is derived, never written down.</b> A hand-listed matrix covers the
/// types someone thought of on the day, which is how this class stayed open: the dict views were
/// bridged, registered and shipped without anyone pairing the two spellings. Cells here are
/// generated by reflecting over <see cref="BuiltinRegistry"/> — for each seed value, every
/// zero-argument method whose return type is a registry-known generic becomes a producer, and its
/// return type becomes the annotation spelling. Add a method like <c>keys()</c> tomorrow and its
/// cells appear with no edit here; that is the property a list cannot have. <see cref="RequiredCells"/>
/// is the floor that keeps the derivation honest, so a probe that silently stops finding producers
/// fails instead of passing over an empty matrix.</para>
///
/// <para><b>Probe.</b> Each cell asks one question in a form that reports the ANSWER and the RESULT
/// TYPE in a single comparable string: the operation is assigned to a <c>bool</c>. A refused
/// operation yields its refusal (SPY0222/SPY0320/…); an accepted one yields SPY0220 naming the type
/// it produced (<c>Cannot assign type 'set[str]' to variable of type 'bool'</c>). So
/// "annotation says set[str], expression says refused" is a visible disagreement rather than two
/// green compilations. Operations probed per producer: <c>len()</c>, iteration, and each of
/// <c>| &amp; - ^ + *</c>.</para>
///
/// <para><b>Ratchet.</b> <c>Conformance/path-agreement-allowlist.txt</c>, per
/// <c>docs/design/gap-discovery-contracts.md</c>: a divergent cell whose key is not listed fails the
/// suite, every listed key cites the issue that will drain it, and a listed cell that has started
/// AGREEING also fails — deleting the line is part of landing the fix.</para>
///
/// <para><b>Mutation test (performed 2026-08-14, recorded here per round mechanics).</b> Reverting
/// the expression path's provenance read — deleting the <c>?? ResolveOriginDefinition(generic)</c>
/// fallback in <c>ClrTypeHelper.TryConstructClosedGeneric</c>, so only the annotation path resolves
/// a CLR type — took the sweep from 5 divergent cells to 13. The eight that flipped are exactly the
/// operator cells the fix repairs: <c>dict.keys()</c> and <c>dict.items()</c> across
/// <c>| &amp; - ^</c> (<c>annotation: SPY0220 set[str]</c> vs <c>expression: SPY0222</c>), plus
/// <c>dict.copy()::op::|</c> and <c>set.copy()::op::|</c> — which is how we learned the provenance
/// fix reaches further than the dict views that motivated it. Restored immediately; the sweep
/// passed again.</para>
///
/// <para><b>Cost.</b> Single-file <c>Analyze</c> per side, no emission or execution, so the whole
/// matrix runs in well under a second — cheap enough for the regular suite, hence no
/// <c>GapDiscovery</c> trait.</para>
/// </summary>
public class AnnotationExpressionPathAgreementTests
{
    private readonly ITestOutputHelper _output;

    public AnnotationExpressionPathAgreementTests(ITestOutputHelper output) => _output = output;

    /// <summary>
    /// Seed values: the roots every producer is reached from. These are VALUES, deliberately not
    /// the types under test — the types under test are whatever the registry says these values'
    /// methods return. Each entry is a Sharpy type annotation and a literal of that type.
    /// </summary>
    private static readonly (string TypeName, string Annotation, string Literal)[] Seeds =
    {
        ("dict", "dict[str, int]", "{\"a\": 1, \"b\": 2}"),
        ("list", "list[int]", "[1, 2, 3]"),
        ("set", "set[int]", "{1, 2, 3}"),
    };

    /// <summary>
    /// The floor: producer keys the derivation MUST rediscover. Not the matrix — the matrix is
    /// derived — this is what makes a derivation that finds nothing fail loudly rather than pass
    /// over an empty set. The dict views are named because they are the #1496/#1497 class itself.
    /// </summary>
    private static readonly string[] RequiredCells =
    {
        "dict.keys()",
        "dict.values()",
        "dict.items()",
    };

    /// <summary>
    /// The operations each producer is probed with, over the cell's two values of the same type.
    /// </summary>
    private static readonly (string Name, Func<string, string, string> Probe)[] Operations =
    {
        ("len", (a, _) => $"len({a})"),
        ("op::|", (a, b) => $"{a} | {b}"),
        ("op::&", (a, b) => $"{a} & {b}"),
        ("op::-", (a, b) => $"{a} - {b}"),
        ("op::^", (a, b) => $"{a} ^ {b}"),
        ("op::+", (a, b) => $"{a} + {b}"),
        ("op::*", (a, b) => $"{a} * {b}"),
    };

    [Fact]
    public void AnnotationAndExpressionPathsAgreeOnEveryBridgedTypeSurface()
    {
        var stopwatch = Stopwatch.StartNew();
        var allowlist = LoadAllowlist();
        var producers = DiscoverProducers();

        foreach (var required in RequiredCells)
        {
            producers.Should().Contain(p => p.Key == required,
                "the producer derivation must still find '{0}'. If it does not, the reflection over "
                + "BuiltinRegistry has stopped seeing method return types and this sweep is measuring "
                + "an empty matrix — which would pass silently. Producers found: {1}",
                required, string.Join(", ", producers.Select(p => p.Key)));
        }

        var results = new List<CellResult>();
        foreach (var producer in producers)
        {
            foreach (var (opName, probe) in Operations)
            {
                var key = $"{producer.Key}::{opName}";
                var annotation = Measure(producer, probe, viaAnnotation: true);
                var expression = Measure(producer, probe, viaAnnotation: false);
                results.Add(Compare(key, producer, annotation, expression));
            }

            // Iteration is asked as a statement rather than an expression, so it gets its own cell
            // shape rather than being bent into the bool-probe form.
            var iterKey = $"{producer.Key}::iterate";
            results.Add(Compare(iterKey, producer,
                MeasureIteration(producer, viaAnnotation: true),
                MeasureIteration(producer, viaAnnotation: false)));
        }

        stopwatch.Stop();

        var divergent = results.Where(r => r.Divergences.Count > 0).ToList();
        var offenders = divergent.Where(r => !allowlist.Contains(r.Key)).ToList();
        var stale = results
            .Where(r => r.Divergences.Count == 0 && allowlist.Contains(r.Key))
            .Select(r => r.Key)
            .ToList();

        WriteReport(new
        {
            harness = "annotation-expression-path-agreement",
            contract = "one runtime type has one surface, however the type system arrived at it "
                + "(#1496/#1497 class; umbrella #1146)",
            scopeNotes = new[]
            {
                "Producers are DERIVED by reflecting over BuiltinRegistry: every zero-argument method "
                + "whose return type is a registry-known generic. Never hand-listed.",
                "Each cell compiles the same operation twice: once on a value bound through a type "
                + "annotation, once on the producing expression inline.",
                "The probe assigns the operation to a bool, so the diagnostic reports the verdict AND "
                + "the result type in one comparable string.",
                "Single-file Analyze only — no emission, no execution.",
            },
            elapsedSeconds = Math.Round(stopwatch.Elapsed.TotalSeconds, 2),
            totals = new
            {
                cells = results.Count,
                producers = producers.Count,
                agreeing = results.Count - divergent.Count,
                divergent = divergent.Count,
                allowlistSize = allowlist.Count,
                nonAllowlisted = offenders.Count,
                staleAllowlistEntries = stale.Count,
            },
            cells = results.Select(r => r.ToReport(allowlist)),
        });

        foreach (var r in results)
            _output.WriteLine($"{(r.Divergences.Count == 0 ? "  ok" : "DIFF")}  {r.Key}");
        _output.WriteLine(
            $"producers: {producers.Count}  cells: {results.Count}  divergent: {divergent.Count}  "
            + $"allowlist: {allowlist.Count}  elapsed: {stopwatch.Elapsed.TotalSeconds:F1}s");

        stale.Should().BeEmpty(
            "an allowlist entry is deleted in the change that fixes its bug, or the ratchet stays "
            + "disarmed on a cell that has started working (docs/design/gap-discovery-contracts.md). "
            + "Delete these lines from Conformance/path-agreement-allowlist.txt:\n  "
            + string.Join("\n  ", stale));

        offenders.Should().BeEmpty(
            "an annotation is a way of NAMING a type, not a different type. Where the two paths "
            + "disagree, at least one is wrong — and #1496 is the proof that they can be wrong in "
            + "OPPOSITE directions simultaneously, so 'the other spelling works' is not evidence. "
            + "Fix the resolution, or file an issue and add the printed cell key to "
            + "Conformance/path-agreement-allowlist.txt citing it.\n"
            + "Divergent cells:\n"
            + string.Join("\n", offenders.Select(o => o.Describe()))
            + "\nFull report: .claude/tmp/path-agreement-conformance-report.json");
    }

    // --- Producer derivation ---------------------------------------------------------------------

    /// <summary>
    /// A value reachable two ways: <c>Setup</c> declares the seed, <c>Call</c> is the expression
    /// producing it, and <c>Annotation</c> is the Sharpy spelling of its type — read off the
    /// registry's own return type, so the annotation path and the expression path are being asked
    /// about a type the compiler itself says they share.
    /// </summary>
    private sealed record Producer(string Key, string SeedAnnotation, string SeedLiteral,
        string Call, string Annotation);

    /// <summary>
    /// Every (seed, zero-argument method) pair whose return type is a registry-known generic type.
    /// Reflection over the registry, so the matrix tracks the registry rather than this file.
    /// </summary>
    private static List<Producer> DiscoverProducers()
    {
        var registry = new BuiltinRegistry();
        var producers = new List<Producer>();

        foreach (var (typeName, seedAnnotation, seedLiteral) in Seeds)
        {
            var seedType = registry.GetType(typeName);
            if (seedType == null)
                continue;

            // The seed's declared type arguments, positionally — used to substitute the registry's
            // type parameters into the concrete return-type spelling (dict's K,V -> str,int).
            var seedArgs = ParseTypeArguments(seedAnnotation);

            foreach (var method in seedType.Methods)
            {
                if (method.Parameters.Count > 0)
                    continue;
                if (method.ReturnType is not GenericType returned)
                    continue;
                if (registry.GetType(returned.Name) == null)
                    continue;

                var annotation = TrySpellType(returned, seedType, seedArgs);
                if (annotation == null)
                    continue;

                producers.Add(new Producer(
                    Key: $"{typeName}.{method.Name}()",
                    SeedAnnotation: seedAnnotation,
                    SeedLiteral: seedLiteral,
                    Call: $"{method.Name}()",
                    Annotation: annotation));
            }
        }

        return producers
            .GroupBy(p => p.Key, StringComparer.Ordinal)
            .Select(g => g.First())
            .OrderBy(p => p.Key, StringComparer.Ordinal)
            .ToList();
    }

    /// <summary>
    /// The Sharpy annotation spelling of a registry return type, with the owning type's parameters
    /// substituted by the seed's concrete arguments. Returns null when any position is not a plain
    /// name or a bound parameter — an unspellable type is skipped rather than guessed at, so a cell
    /// never compares two programs that differ by more than the spelling under test.
    /// </summary>
    private static string? TrySpellType(SemanticType type, TypeSymbol owner, IReadOnlyList<string> seedArgs)
    {
        switch (type)
        {
            case BuiltinType b:
                return b.Name;

            case TypeParameterType p:
            {
                var index = owner.TypeParameters.FindIndex(tp => tp.Name == p.Name);
                return index >= 0 && index < seedArgs.Count ? seedArgs[index] : null;
            }

            case GenericType g:
            {
                var args = new List<string>();
                foreach (var arg in g.TypeArguments)
                {
                    var spelled = TrySpellType(arg, owner, seedArgs);
                    if (spelled == null)
                        return null;
                    args.Add(spelled);
                }
                return args.Count == 0 ? g.Name : $"{g.Name}[{string.Join(", ", args)}]";
            }

            default:
                return null;
        }
    }

    /// <summary>Splits <c>dict[str, int]</c> into <c>["str", "int"]</c> at depth 1.</summary>
    private static List<string> ParseTypeArguments(string annotation)
    {
        var open = annotation.IndexOf('[', StringComparison.Ordinal);
        if (open < 0 || !annotation.EndsWith("]", StringComparison.Ordinal))
            return new List<string>();

        var inner = annotation.Substring(open + 1, annotation.Length - open - 2);
        var args = new List<string>();
        var depth = 0;
        var start = 0;
        for (var i = 0; i < inner.Length; i++)
        {
            switch (inner[i])
            {
                case '[': depth++; break;
                case ']': depth--; break;
                case ',' when depth == 0:
                    args.Add(inner.Substring(start, i - start).Trim());
                    start = i + 1;
                    break;
            }
        }
        args.Add(inner.Substring(start).Trim());
        return args;
    }

    // --- Measurement ---------------------------------------------------------------------------

    private sealed record Measurement(string Path, string Verdict, string Program);

    /// <summary>
    /// The bool-probe program. <c>viaAnnotation</c> selects which producer spelling is measured:
    /// the value bound through its declared type, or the call used inline. Everything else about the
    /// two programs is character-identical, so any difference in the verdict is the paths diverging.
    /// </summary>
    private Measurement Measure(
        Producer producer, Func<string, string, string> probe, bool viaAnnotation)
    {
        var setup =
            $"    s1: {producer.SeedAnnotation} = {producer.SeedLiteral}\n"
            + $"    s2: {producer.SeedAnnotation} = {producer.SeedLiteral}\n";

        string left, right;
        if (viaAnnotation)
        {
            setup +=
                $"    v: {producer.Annotation} = s1.{producer.Call}\n"
                + $"    v2: {producer.Annotation} = s2.{producer.Call}\n";
            (left, right) = ("v", "v2");
        }
        else
        {
            (left, right) = ($"s1.{producer.Call}", $"s2.{producer.Call}");
        }

        // The probe expression is bound where its type is REPORTED: assigning to bool makes an
        // accepted operation announce its result type through SPY0220, and leaves a refused one
        // announcing its refusal. Both are the answer this sweep compares.
        var program = "def main() -> None:\n" + setup
            + $"    probe: bool = {probe(left, right)}\n";

        return new Measurement(viaAnnotation ? "annotation" : "expression", Analyze(program), program);
    }

    /// <summary>Iteration asked as a statement — <c>for _ in value:</c> — rather than as an expression.</summary>
    private Measurement MeasureIteration(Producer producer, bool viaAnnotation)
    {
        var setup = $"    s1: {producer.SeedAnnotation} = {producer.SeedLiteral}\n";
        string value;
        if (viaAnnotation)
        {
            setup += $"    v: {producer.Annotation} = s1.{producer.Call}\n";
            value = "v";
        }
        else
        {
            value = $"s1.{producer.Call}";
        }

        var program = "def main() -> None:\n" + setup
            + $"    for item in {value}:\n        print(item)\n";
        return new Measurement(viaAnnotation ? "annotation" : "expression", Analyze(program), program);
    }

    /// <summary>
    /// The cell's answer: the error diagnostics, code and message, normalized so that the only text
    /// that survives is what the compiler concluded. The annotation path names its binding
    /// (<c>v</c>/<c>v2</c>) where the expression path names a call, so those spellings are erased —
    /// otherwise every cell would "diverge" on the difference the sweep deliberately introduced.
    /// </summary>
    private static string Analyze(string program)
    {
        var result = new CompilerApi().Analyze(program);
        var errors = result.Diagnostics
            .Where(d => d.Severity == CompilerDiagnosticSeverity.Error)
            .Select(d => $"{d.Code}: {Normalize(d.Message)}")
            .OrderBy(m => m, StringComparer.Ordinal)
            .ToList();

        return errors.Count == 0 ? "<accepted>" : string.Join(" | ", errors);
    }

    private static readonly Regex QuotedSpelling = new(@"'(v2?|s[12]\.[a-z_0-9]+\(\))'",
        RegexOptions.Compiled);

    private static string Normalize(string message) => QuotedSpelling.Replace(message, "'<value>'");

    private static CellResult Compare(
        string key, Producer producer, Measurement annotation, Measurement expression)
    {
        var divergences = new List<string>();
        if (annotation.Verdict != expression.Verdict)
        {
            divergences.Add(
                $"verdict — annotation: {annotation.Verdict}   expression: {expression.Verdict}");
        }
        return new CellResult(key, producer, annotation, expression, divergences);
    }

    private sealed record CellResult(
        string Key, Producer Producer, Measurement Annotation, Measurement Expression,
        IReadOnlyList<string> Divergences)
    {
        public string Describe()
            => $"  {Key}\n" + string.Join("\n", Divergences.Select(d => "      " + d));

        public object ToReport(Allowlist allowlist) => new
        {
            key = Key,
            agrees = Divergences.Count == 0,
            allowlisted = allowlist.Contains(Key),
            divergences = Divergences,
            annotation = new { verdict = Annotation.Verdict },
            expression = new { verdict = Expression.Verdict },
            // Programs for divergent cells only, so the report reproduces a failure without
            // re-deriving it from the producer table.
            programs = Divergences.Count == 0
                ? null
                : new { annotation = Annotation.Program, expression = Expression.Program },
        };
    }

    // --- allowlist + report I/O ------------------------------------------------------------------

    private static readonly Lazy<string?> AllowlistPath = new(FindAllowlistPath);

    private static Allowlist LoadAllowlist()
    {
        var exact = new HashSet<string>(StringComparer.Ordinal);
        var path = AllowlistPath.Value;
        if (path == null || !File.Exists(path))
        {
            throw new InvalidOperationException(
                "Conformance/path-agreement-allowlist.txt is missing. Its presence is what arms the "
                + "ratchet; deleting it would silently disarm the sweep rather than relax it.");
        }

        foreach (var raw in File.ReadAllLines(path))
        {
            var line = raw;
            var hash = line.IndexOf('#', StringComparison.Ordinal);
            if (hash >= 0)
                line = line.Substring(0, hash);
            line = line.Trim();
            if (line.Length > 0)
                exact.Add(line);
        }

        return new Allowlist(exact);
    }

    private static string? FindAllowlistPath()
    {
        var current = AppContext.BaseDirectory;
        while (current != null)
        {
            var dir = Path.Combine(current, "src", "Sharpy.Compiler.Tests", "Conformance");
            if (Directory.Exists(dir))
                return Path.Combine(dir, "path-agreement-allowlist.txt");
            current = Directory.GetParent(current)?.FullName;
        }
        return null;
    }

    private void WriteReport(object report)
    {
        var reportDir = Path.GetFullPath(Path.Combine(
            Path.GetDirectoryName(typeof(AnnotationExpressionPathAgreementTests).Assembly.Location)!,
            "..", "..", "..", "..", "..", ".claude", "tmp"));
        Directory.CreateDirectory(reportDir);
        var reportPath = Path.Combine(reportDir, "path-agreement-conformance-report.json");
        File.WriteAllText(reportPath,
            JsonSerializer.Serialize(report, new JsonSerializerOptions { WriteIndented = true }));
        _output.WriteLine($"Report written to: {reportPath}");
    }

    /// <summary>The reviewed conformance allowlist: exact <c>producer::operation</c> keys.</summary>
    internal sealed class Allowlist
    {
        private readonly HashSet<string> _exact;
        public Allowlist(HashSet<string> exact) => _exact = exact;
        public int Count => _exact.Count;
        public bool Contains(string key) => _exact.Contains(key);
    }
}
