using Sharpy.Compiler.Diagnostics;
using Xunit;
using Xunit.Abstractions;

namespace Sharpy.Compiler.Tests.Fuzz;

/// <summary>
/// Property-based tests for the Sharpy semantic pipeline (Phase 2b).
/// These tests verify correctness invariants that should hold for any input:
/// no internal compiler errors, deterministic diagnostics, and whitespace insensitivity.
/// </summary>
[Trait("Category", "Property")]
[Trait("Speed", "Slow")]
[Collection("HeavyCompilation")]
public class SemanticPropertyTests
{
    private readonly ITestOutputHelper _output;

    /// <summary>
    /// Timeout per fuzz iteration (2 seconds).
    /// </summary>
    private const int FuzzIterationTimeoutMs = 2000;

    public SemanticPropertyTests(ITestOutputHelper output)
    {
        _output = output;
    }

    /// <summary>
    /// Property: Well-formed programs compile without internal errors.
    /// Programs generated by SharpyFuzzer.GenerateValidLooking() should produce
    /// only user-facing errors (SPY codes), never InternalCompilerErrorException.
    /// If compilation fails, all diagnostics should have proper SPY codes.
    /// </summary>
    [Theory]
    [InlineData(42)]
    [InlineData(123)]
    [InlineData(7777)]
    [InlineData(2025)]
    [InlineData(9999)]
    public void WellFormedPrograms_NeverThrowInternalCompilerError(int seed)
    {
        var fuzzer = new SharpyFuzzer(seed);
        var compiler = new Compiler();
        var failures = new List<string>();

        for (int i = 0; i < 50; i++)
        {
            var source = fuzzer.GenerateValidLooking();
            try
            {
                using var cts = new CancellationTokenSource(TimeSpan.FromMilliseconds(FuzzIterationTimeoutMs));
                var result = compiler.Compile(source, "fuzz_semantic.spy", cts.Token);

                // If compilation failed, verify no diagnostic indicates an internal error
                if (!result.Success)
                {
                    foreach (var diag in result.Diagnostics.GetAll())
                    {
                        if (diag.Message.Contains("Internal compiler error", StringComparison.OrdinalIgnoreCase) ||
                            diag.Message.Contains("InternalCompilerErrorException", StringComparison.OrdinalIgnoreCase))
                        {
                            failures.Add(
                                $"Seed {seed}, iter {i}: Internal compiler error in diagnostic: {diag.Message}");
                        }
                    }
                }
            }
            catch (InternalCompilerErrorException ex)
            {
                failures.Add(
                    $"Seed {seed}, iter {i}: InternalCompilerErrorException in {ex.Component}: {ex.Message}\n" +
                    $"Input: {Truncate(source)}");
            }
            catch (OperationCanceledException)
            {
                // Timeouts are acceptable for random inputs
            }
            catch (Exception ex) when (ex is not InternalCompilerErrorException)
            {
                // Other exceptions are tested in FuzzTests; we only care about ICE here
            }
        }

        if (failures.Count > 0)
        {
            foreach (var f in failures)
                _output.WriteLine(f);
        }

        Assert.Empty(failures);
    }

    /// <summary>
    /// Property: Error count is deterministic.
    /// Compiling the same source twice should produce the same number and codes of diagnostics.
    /// </summary>
    [Theory]
    [InlineData(42)]
    [InlineData(123)]
    [InlineData(7777)]
    [InlineData(2025)]
    [InlineData(9999)]
    public void Compilation_IsDeterministic(int seed)
    {
        var fuzzer = new SharpyFuzzer(seed);
        var failures = new List<string>();

        for (int i = 0; i < 50; i++)
        {
            var source = fuzzer.GenerateValidLooking();
            try
            {
                var compiler1 = new Compiler();
                var compiler2 = new Compiler();

                using var cts1 = new CancellationTokenSource(TimeSpan.FromMilliseconds(FuzzIterationTimeoutMs));
                using var cts2 = new CancellationTokenSource(TimeSpan.FromMilliseconds(FuzzIterationTimeoutMs));

                var result1 = compiler1.Compile(source, "fuzz_det.spy", cts1.Token);
                var result2 = compiler2.Compile(source, "fuzz_det.spy", cts2.Token);

                var diags1 = result1.Diagnostics.GetAll();
                var diags2 = result2.Diagnostics.GetAll();

                // Same number of diagnostics
                if (diags1.Count != diags2.Count)
                {
                    failures.Add(
                        $"Seed {seed}, iter {i}: Diagnostic count differs: {diags1.Count} vs {diags2.Count}\n" +
                        $"Input: {Truncate(source)}");
                    continue;
                }

                // Same diagnostic codes in the same order
                for (int d = 0; d < diags1.Count; d++)
                {
                    if (diags1[d].Code != diags2[d].Code)
                    {
                        failures.Add(
                            $"Seed {seed}, iter {i}: Diagnostic[{d}] code differs: " +
                            $"'{diags1[d].Code}' vs '{diags2[d].Code}'\n" +
                            $"Input: {Truncate(source)}");
                        break;
                    }
                }
            }
            catch (OperationCanceledException)
            {
                // Timeouts are OK
            }
            catch (Exception)
            {
                // Crashes are tested elsewhere
            }
        }

        if (failures.Count > 0)
        {
            foreach (var f in failures)
                _output.WriteLine(f);
        }

        Assert.Empty(failures);
    }

    /// <summary>
    /// Property: Adding a trailing newline doesn't change semantics.
    /// Source with/without trailing newline should produce the same diagnostic codes.
    /// </summary>
    [Theory]
    [InlineData(42)]
    [InlineData(123)]
    [InlineData(7777)]
    [InlineData(2025)]
    [InlineData(9999)]
    public void TrailingNewline_DoesNotChangeDiagnostics(int seed)
    {
        var fuzzer = new SharpyFuzzer(seed);
        var failures = new List<string>();

        for (int i = 0; i < 50; i++)
        {
            var source = fuzzer.GenerateValidLooking();

            // Ensure source does NOT end with newline for the base case
            var trimmed = source.TrimEnd('\n', '\r');
            var withNewline = trimmed + "\n";

            try
            {
                var compiler1 = new Compiler();
                var compiler2 = new Compiler();

                using var cts1 = new CancellationTokenSource(TimeSpan.FromMilliseconds(FuzzIterationTimeoutMs));
                using var cts2 = new CancellationTokenSource(TimeSpan.FromMilliseconds(FuzzIterationTimeoutMs));

                var result1 = compiler1.Compile(trimmed, "fuzz_nl.spy", cts1.Token);
                var result2 = compiler2.Compile(withNewline, "fuzz_nl.spy", cts2.Token);

                // Extract error codes (ignore warnings since newlines may affect warning positions)
                var errorCodes1 = result1.Diagnostics.GetErrors()
                    .Select(d => d.Code ?? d.Message)
                    .ToList();
                var errorCodes2 = result2.Diagnostics.GetErrors()
                    .Select(d => d.Code ?? d.Message)
                    .ToList();

                if (errorCodes1.Count != errorCodes2.Count)
                {
                    failures.Add(
                        $"Seed {seed}, iter {i}: Error count differs with/without trailing newline: " +
                        $"{errorCodes1.Count} vs {errorCodes2.Count}\n" +
                        $"Without: [{string.Join(", ", errorCodes1)}]\n" +
                        $"With:    [{string.Join(", ", errorCodes2)}]\n" +
                        $"Input: {Truncate(source)}");
                    continue;
                }

                for (int d = 0; d < errorCodes1.Count; d++)
                {
                    if (errorCodes1[d] != errorCodes2[d])
                    {
                        failures.Add(
                            $"Seed {seed}, iter {i}: Error[{d}] code differs: " +
                            $"'{errorCodes1[d]}' vs '{errorCodes2[d]}'\n" +
                            $"Input: {Truncate(source)}");
                        break;
                    }
                }
            }
            catch (OperationCanceledException)
            {
                // Timeouts OK
            }
            catch (Exception)
            {
                // Crashes tested elsewhere
            }
        }

        if (failures.Count > 0)
        {
            foreach (var f in failures)
                _output.WriteLine(f);
        }

        Assert.Empty(failures);
    }

    private static string Truncate(string s, int maxLen = 200)
    {
        if (s.Length <= maxLen)
            return s.Replace("\n", "\\n").Replace("\r", "\\r").Replace("\t", "\\t");
        return s[..maxLen].Replace("\n", "\\n").Replace("\r", "\\r").Replace("\t", "\\t") + "...";
    }
}
