extern alias SharpyRT;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.Loader;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Emit;
using Sharpy.Compiler.CodeGen;
using Sharpy.Compiler.Diagnostics;
using Sharpy.Compiler.Logging;
using Sharpy.Compiler.Lowering;
using Sharpy.Compiler.Model;
using Sharpy.Compiler.Parser.Ast;
using Sharpy.Compiler.Semantic;
using Sharpy.Compiler.Semantic.Registry;
using Sharpy.Compiler.Utilities;

namespace Sharpy.Compiler.Project;

internal partial class ProjectCompiler
{
    /// <summary>
    /// Maximum size (in bytes) of source a single generator invocation may produce.
    /// Output that exceeds this limit is rejected with SPY0550 to prevent runaway
    /// generators from exhausting memory or compile time.
    /// </summary>
    private const int MaxGeneratedSourceBytes = 102_400;

    private GeneratorPartition PartitionGenerators()
    {
        _logger.LogInfo("Phase 4d: Partitioning source generators");

        var generatorFiles = new List<string>();
        var generatorTypes = new List<TypeSymbol>();

        foreach (var (filePath, unit) in _projectModel!.Units)
        {
            if (unit.Phase == CompilationPhase.Failed || unit.Ast == null)
                continue;

            // A project's type declarations live in their file's MODULE SCOPE, not the global
            // scope — a bare-name lookup at global scope returns null (#1431). Enter the module
            // scope before resolving each ClassDef's symbol, exactly as code generation does
            // (ProjectCompiler.CodeGen.cs). Without this the partition found nothing: every
            // generator trigger fell through to the emitter as a plain bracket attribute and came
            // back as CS0616 ("... is not an attribute class") behind SPY0908. IsSourceGenerator is
            // already set on the symbol here (inheritance resolved in Phase 4b/4c) — the flag was
            // never the miss; reaching the symbol was.
            SymbolTable.EnterModuleScope(unit.ModulePath);
            try
            {
                foreach (var statement in unit.Ast.Body)
                {
                    if (statement is ClassDef classDef)
                    {
                        var symbol = SymbolTable.Lookup(classDef.Name) as TypeSymbol;
                        if (symbol is { IsSourceGenerator: true })
                        {
                            if (!generatorFiles.Contains(filePath))
                                generatorFiles.Add(filePath);
                            generatorTypes.Add(symbol);
                        }
                    }
                }
            }
            finally
            {
                SymbolTable.ExitScope();
            }
        }

        if (generatorFiles.Count > 0)
        {
            _logger.LogInfo($"Found {generatorTypes.Count} source generator(s) in {generatorFiles.Count} file(s)");
        }

        return new GeneratorPartition(generatorFiles, generatorTypes);
    }

    private bool ExecuteGeneratorPipeline(
        GeneratorPartition partition,
        FileCompilationPipeline pipeline,
        ProjectConfig config,
        CancellationToken cancellationToken)
    {
        _logger.LogInfo("Phase 5b: Executing source generators");

        // Stage 1: Compile generator files to an in-memory assembly
        var generatorAssembly = CompileGeneratorAssembly(partition, config, cancellationToken);
        if (generatorAssembly == null)
            return false;

        // Stage 2: Execute generators against their target declarations
        var generatedSources = ExecuteGenerators(generatorAssembly, cancellationToken);
        if (generatedSources == null)
            return false;

        if (generatedSources.Count == 0)
        {
            _logger.LogInfo("No source was generated by any generator");
            return true;
        }

        // Stage 3: Re-parse generated source and merge into the compilation
        if (!IntegrateGeneratedSource(generatedSources, pipeline, config, cancellationToken))
            return false;

        _logger.LogInfo($"Source generator pipeline completed: {generatedSources.Count} generation(s) produced");
        return true;
    }

    private Assembly? CompileGeneratorAssembly(
        GeneratorPartition partition,
        ProjectConfig config,
        CancellationToken cancellationToken)
    {
        _logger.LogInfo("Stage 1: Compiling generator files to assembly");

        var generatorCSharp = new Dictionary<string, string>();
        // D3 (#1050): trees the emitter built for freshly-generated generator files, keyed
        // by the same path as generatorCSharp. Files served from cached text (below) have no
        // tree and are reparsed when the generator assembly is compiled.
        var generatorTrees = new Dictionary<string, SyntaxTree>();
        var builtinRegistry = SymbolTable.BuiltinRegistry;

        var generatorModules = partition.GeneratorFiles
            .Select(fp => _projectModel!.Units[fp])
            .Where(unit => unit.Ast != null)
            .OrderBy(unit => unit.FilePath, StringComparer.Ordinal)
            .Select(unit => (unit.FilePath, unit.Ast!))
            .ToList();
        var generatorIr = new LoweringPass().Lower(generatorModules, SemanticInfo, SymbolTable);

        foreach (var filePath in partition.GeneratorFiles)
        {
            var unit = _projectModel!.Units[filePath];
            if (unit.GeneratedCSharp != null)
            {
                generatorCSharp[filePath] = unit.GeneratedCSharp;
                continue;
            }

            var isEntryPoint = false;
            var isPackageInit = unit.ModulePath.EndsWith("__init__", StringComparison.Ordinal);

            var codeGenContext = new CodeGenContext(SymbolTable, builtinRegistry)
            {
                TargetsTestHost = config.TestHost,
                SourceFilePath = filePath,
                ProjectNamespace = config.RootNamespace,
                ProjectRootPath = ComputeSourceRootPath(config),
                IsEntryPoint = isEntryPoint,
                IsPackageInit = isPackageInit,
                Logger = _logger,
                SemanticBinding = _projectModel.SemanticBinding,
                SemanticInfo = SemanticInfo,
                Ir = generatorIr,
                Features = ImportResolver.GetEffectiveFeatures(_features, filePath)
            };

            // Enter the file's module scope before emitting, exactly as the main code-generation
            // path does (ProjectCompiler.CodeGen.cs) — name resolution during emission (base-type
            // qualification, override detection, constructor binding) resolves from the correct
            // scope. Without it the emitter fell back to bare names, producing a generator assembly
            // that referenced an unqualified `SourceGenerator` / `GeneratorOutput` no reference
            // could satisfy — CS0246 surfaced as SPY0550 the moment a generator was actually
            // partitioned (#1431). The main compilation qualifies these correctly because it enters
            // the scope; this path is its sibling and must do the same.
            SymbolTable.EnterModuleScope(unit.ModulePath);
            Microsoft.CodeAnalysis.CSharp.Syntax.CompilationUnitSyntax roslynUnit;
            try
            {
                var emitter = _emitterFactory.Create(codeGenContext, cancellationToken);
                roslynUnit = emitter.GenerateCompilationUnit(unit.Ast!);
            }
            finally
            {
                SymbolTable.ExitScope();
            }
            var csharpCode = roslynUnit.ToFullString();

            if (codeGenContext.HasErrors)
            {
                _diagnostics.Merge(codeGenContext.Diagnostics);
                return null;
            }

            generatorCSharp[filePath] = csharpCode;
            // The emitter's tree is handed directly to CSharpCompilation (zero-parse, #1095) —
            // matches the hot path in ProjectCompiler.CodeGen.cs; ReparseEquivalenceConformanceTests
            // guarantees Create(root) binds identically to ParseText(root.ToFullString()).
            //
            // Source generators emit no #line directives, so no post-processing runs here — this is
            // the same zero-parse handoff as the EmitLineDirectives-off branch in
            // ProjectCompiler.CodeGen.cs. (The directives-on hot path there reparses by choice, #1126.)
            generatorTrees[filePath] = CSharpSyntaxTree.Create(
                roslynUnit,
                options: CSharpParseOptions.Default,
                path: filePath,
                encoding: System.Text.Encoding.UTF8);
        }

        try
        {
            var syntaxTrees = generatorCSharp.Select(kvp =>
                generatorTrees.TryGetValue(kvp.Key, out var prebuilt)
                    ? prebuilt
                    : CSharpSyntaxTree.ParseText(kvp.Value, path: kvp.Key,
                        encoding: System.Text.Encoding.UTF8)).ToList();

            var references = AssemblyCompiler.GetDefaultReferences();
            var compilation = CSharpCompilation.Create(
                config.RootNamespace + ".Generators",
                syntaxTrees,
                references,
                new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary)
                    .WithOptimizationLevel(OptimizationLevel.Debug));

            using var ms = new MemoryStream();
            var emitResult = compilation.Emit(ms);

            if (!emitResult.Success)
            {
                var errors = emitResult.Diagnostics
                    .Where(d => d.Severity == DiagnosticSeverity.Error)
                    .Select(d => d.GetMessage(System.Globalization.CultureInfo.InvariantCulture))
                    .Take(3);
                _diagnostics.AddError(
                    $"Failed to compile source generator assembly: {string.Join("; ", errors)}",
                    code: DiagnosticCodes.CodeGen.GeneratorExecutionError);
                return null;
            }

            ms.Seek(0, SeekOrigin.Begin);
            var loadContext = new AssemblyLoadContext("SharplyGenerators", isCollectible: true);
            var assembly = loadContext.LoadFromStream(ms);

            _logger.LogInfo($"Generator assembly compiled: {assembly.GetName().Name}");
            return assembly;
        }
        catch (Exception ex)
        {
            _diagnostics.AddError(
                $"Source generator assembly compilation failed: {ex.Message}",
                code: DiagnosticCodes.CodeGen.GeneratorExecutionError);
            return null;
        }
    }

    private List<GeneratedSource>? ExecuteGenerators(
        Assembly generatorAssembly,
        CancellationToken cancellationToken)
    {
        _logger.LogInfo("Stage 2: Executing generators against target declarations");

        var results = new List<GeneratedSource>();
        var contextBuilder = new GeneratorContextBuilder(SemanticInfo, _projectModel!.SemanticBinding, _logger);

        // Defense-in-depth: track which (generator type, target declaration) pairs we've
        // already executed during this pipeline run. The semantic phase normally prevents
        // duplicate bindings, but if one slips through we want to detect it instead of
        // silently producing duplicate output.
        var executedPairs = new HashSet<string>(StringComparer.Ordinal);

        foreach (var (declaration, bindings) in SemanticInfo.GetAllGeneratorBindings())
        {
            foreach (var binding in bindings)
            {
                cancellationToken.ThrowIfCancellationRequested();

                var generatorTypeName = binding.GeneratorType.Name;
                _logger.LogDebug($"Executing generator '{generatorTypeName}'");

                var pairKey = generatorTypeName + "::" + RuntimeHelpers.GetHashCode(declaration).ToString(System.Globalization.CultureInfo.InvariantCulture);
                if (!executedPairs.Add(pairKey))
                {
                    _logger.LogWarning(
                        $"Source generator '{generatorTypeName}' was invoked more than once for the same target; skipping duplicate invocation",
                        binding.Trigger.LineStart, binding.Trigger.ColumnStart);
                    continue;
                }

                var targetFilePath = FindFileForDeclaration(declaration);
                var generatorFilePath = binding.GeneratorType.DefiningFilePath;
                var argumentsHash = ComputeDecoratorArgumentsHash(binding.Trigger);
                var generatorIdentity = generatorTypeName + "@" + GetDeclarationName(declaration);

                // Record target -> generator dependency so a generator file edit
                // invalidates every target it generates code for.
                if (targetFilePath is not null && generatorFilePath is not null)
                {
                    var key = PathNormalizer.Normalize(targetFilePath);
                    if (!_generatorDependencies.TryGetValue(key, out var deps))
                    {
                        deps = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
                        _generatorDependencies[key] = deps;
                    }
                    deps.Add(PathNormalizer.Normalize(generatorFilePath));
                }

                // Cache hit: reuse the previously-generated Sharpy source if nothing
                // it depends on has changed.
                if (_incrementalCache is not null
                    && targetFilePath is not null
                    && generatorFilePath is not null
                    && _incrementalCache.IsGeneratorCacheValid(
                        targetFilePath, generatorIdentity, generatorFilePath, argumentsHash, out var cachedSource)
                    && cachedSource is not null)
                {
                    _logger.LogDebug($"Generator '{generatorTypeName}' cache hit for {generatorIdentity}");
                    results.Add(new GeneratedSource(
                        Source: cachedSource,
                        GeneratorName: generatorTypeName,
                        TargetName: GetDeclarationName(declaration),
                        TriggerDecorator: binding.Trigger,
                        TargetDeclaration: declaration));
                    continue;
                }

                var genType = generatorAssembly.GetTypes()
                    .FirstOrDefault(t => t.Name == generatorTypeName
                        || t.Name == Shared.NameMangler.ToPascalCase(generatorTypeName));

                if (genType == null)
                {
                    _diagnostics.AddError(
                        $"Source generator type '{generatorTypeName}' not found in compiled generator assembly",
                        binding.Trigger.LineStart, binding.Trigger.ColumnStart,
                        code: DiagnosticCodes.CodeGen.GeneratorExecutionError);
                    continue;
                }

                try
                {
                    var generator = Activator.CreateInstance(genType)
                        as SharpyRT::Sharpy.Generators.SourceGenerator;

                    if (generator == null)
                    {
                        _diagnostics.AddError(
                            $"Failed to instantiate source generator '{generatorTypeName}'",
                            binding.Trigger.LineStart, binding.Trigger.ColumnStart,
                            code: DiagnosticCodes.CodeGen.GeneratorExecutionError);
                        continue;
                    }

                    var context = contextBuilder.Build(declaration, binding.Trigger, _projectModel.Config.RootNamespace);

                    // Execute with timeout
                    var task = Task.Run(() => generator.Generate(context), cancellationToken);
                    if (!task.Wait(TimeSpan.FromSeconds(30), cancellationToken))
                    {
                        _diagnostics.AddError(
                            $"Source generator '{generatorTypeName}' timed out after 30s",
                            binding.Trigger.LineStart, binding.Trigger.ColumnStart,
                            code: DiagnosticCodes.CodeGen.GeneratorTimeout);
                        continue;
                    }
                    var output = task.Result;

                    if (output?.Diagnostics != null)
                    {
                        foreach (var diag in output.Diagnostics)
                        {
                            if (diag.Severity == SharpyRT::Sharpy.Generators.GeneratorDiagnosticSeverity.Error)
                            {
                                _diagnostics.AddError(
                                    $"[{generatorTypeName}] {diag.Message}",
                                    binding.Trigger.LineStart, binding.Trigger.ColumnStart,
                                    code: DiagnosticCodes.CodeGen.GeneratorExecutionError);
                            }
                            else if (diag.Severity == SharpyRT::Sharpy.Generators.GeneratorDiagnosticSeverity.Warning)
                            {
                                _diagnostics.AddWarning(
                                    $"[{generatorTypeName}] {diag.Message}",
                                    binding.Trigger.LineStart, binding.Trigger.ColumnStart);
                            }
                        }
                    }

                    if (string.IsNullOrWhiteSpace(output?.Source))
                    {
                        _diagnostics.AddWarning(
                            $"Source generator '{generatorTypeName}' returned empty output",
                            binding.Trigger.LineStart, binding.Trigger.ColumnStart,
                            code: DiagnosticCodes.CodeGen.GeneratorEmptyOutput);
                        continue;
                    }

                    var sourceByteCount = System.Text.Encoding.UTF8.GetByteCount(output.Source);
                    if (sourceByteCount > MaxGeneratedSourceBytes)
                    {
                        _diagnostics.AddError(
                            $"Source generator '{generatorTypeName}' output exceeds {MaxGeneratedSourceBytes / 1024}KB limit (got {sourceByteCount} bytes)",
                            binding.Trigger.LineStart, binding.Trigger.ColumnStart,
                            code: DiagnosticCodes.CodeGen.GeneratorExecutionError);
                        continue;
                    }

                    var targetName = GetDeclarationName(declaration);

                    results.Add(new GeneratedSource(
                        Source: output.Source,
                        GeneratorName: generatorTypeName,
                        TargetName: targetName,
                        TriggerDecorator: binding.Trigger,
                        TargetDeclaration: declaration));

                    // Cache the successful generation so an unchanged subsequent
                    // build can skip the generator. We hash the generator source
                    // (so editing the generator invalidates) and the decorator
                    // arguments (so changing args invalidates).
                    if (_incrementalCache is not null
                        && targetFilePath is not null
                        && generatorFilePath is not null
                        && File.Exists(generatorFilePath))
                    {
                        var generatorHash = IncrementalCompilationCache.ComputeFileHash(generatorFilePath);
                        var targetHash = ComputeDeclarationHash(declaration);
                        _incrementalCache.CacheGeneratorOutput(
                            targetFilePath,
                            generatorIdentity,
                            generatorHash,
                            targetHash,
                            argumentsHash,
                            output.Source);
                    }
                }
                catch (TargetInvocationException tie) when (tie.InnerException != null)
                {
                    _diagnostics.AddError(
                        $"Source generator '{generatorTypeName}' failed: {tie.InnerException.Message}",
                        binding.Trigger.LineStart, binding.Trigger.ColumnStart,
                        code: DiagnosticCodes.CodeGen.GeneratorExecutionError);
                }
                catch (Exception ex) when (ex is not OperationCanceledException)
                {
                    _diagnostics.AddError(
                        $"Source generator '{generatorTypeName}' failed: {ex.Message}",
                        binding.Trigger.LineStart, binding.Trigger.ColumnStart,
                        code: DiagnosticCodes.CodeGen.GeneratorExecutionError);
                }
            }
        }

        return results;
    }

    private bool IntegrateGeneratedSource(
        List<GeneratedSource> generatedSources,
        FileCompilationPipeline pipeline,
        ProjectConfig config,
        CancellationToken cancellationToken)
    {
        _logger.LogInfo("Stage 3: Integrating generated source into compilation");

        foreach (var genSource in generatedSources)
        {
            cancellationToken.ThrowIfCancellationRequested();

            var syntheticPath = $"<generated:{genSource.GeneratorName}:{genSource.TargetName}>";
            _logger.LogDebug($"Parsing generated source: {syntheticPath}");

            // Lex and parse the generated source
            var sourceText = new Text.SourceText(genSource.Source, syntheticPath);
            var lexResult = FileCompilationPipeline.Lex(sourceText, _logger);
            if (lexResult.HasErrors)
            {
                _diagnostics.AddError(
                    $"Source generator '{genSource.GeneratorName}' produced source with lexer errors",
                    genSource.TriggerDecorator.LineStart, genSource.TriggerDecorator.ColumnStart,
                    code: DiagnosticCodes.CodeGen.GeneratorInvalidSource);
                continue;
            }

            var parseResult = FileCompilationPipeline.Parse(lexResult.Tokens, _logger);
            if (parseResult.HasErrors)
            {
                _diagnostics.AddError(
                    $"Source generator '{genSource.GeneratorName}' produced source with parse errors",
                    genSource.TriggerDecorator.LineStart, genSource.TriggerDecorator.ColumnStart,
                    code: DiagnosticCodes.CodeGen.GeneratorInvalidSource);
                continue;
            }

            var module = parseResult.Module;
            if (module == null)
                continue;

            // Find the target file and merge generated statements
            var targetFile = FindFileForDeclaration(genSource.TargetDeclaration);
            if (targetFile == null)
                continue;

            var targetUnit = _projectModel!.Units[targetFile];
            if (targetUnit.Ast == null)
                continue;

            // Refuse generated declarations with base clauses — inheritance froze at Phase 4c
            // and IntegrateGeneratedSource never runs ResolveInheritance (#1535).
            bool hasUnsupportedShape = false;
            foreach (var stmt in module.Body)
            {
                IReadOnlyList<Parser.Ast.TypeAnnotation>? bases = stmt switch
                {
                    Parser.Ast.ClassDef cd => cd.BaseClasses,
                    Parser.Ast.StructDef sd => sd.BaseClasses,
                    _ => null
                };
                if (bases is { Count: > 0 })
                {
                    _diagnostics.AddError(
                        $"Source generator '{genSource.GeneratorName}' emitted a declaration with base types, " +
                        "which is not yet supported. Declare the class in ordinary source or emit members only.",
                        genSource.TriggerDecorator.LineStart, genSource.TriggerDecorator.ColumnStart,
                        code: DiagnosticCodes.CodeGen.GeneratorUnsupportedShape);
                    hasUnsupportedShape = true;
                }
            }
            if (hasUnsupportedShape)
                continue;

            // Add generated statements to the target module's AST, and record each
            // generated statement in SemanticInfo so LSP / tooling can attribute it
            // back to the generator (Phase 7 — "Generated by @[X]" on hover).
            var existingStatements = targetUnit.Ast.Body.ToList();
            foreach (var generatedStmt in module.Body)
            {
                SemanticInfo.MarkAsGenerated(generatedStmt, genSource.GeneratorName);
                existingStatements.Add(generatedStmt);
            }
            targetUnit.Ast = targetUnit.Ast with
            {
                Body = System.Collections.Immutable.ImmutableArray.CreateRange(existingStatements)
            };

            // Invalidate cached C# so codegen re-processes this file
            targetUnit.GeneratedCSharp = null;

            // Run name resolution on generated declarations
            var nameResolveResult = pipeline.ResolveNames(module, cancellationToken);
            foreach (var error in nameResolveResult.Diagnostics.GetErrors())
            {
                _diagnostics.AddError(
                    $"In generated code from @[{genSource.GeneratorName}]: {error.Message}",
                    genSource.TriggerDecorator.LineStart, genSource.TriggerDecorator.ColumnStart,
                    code: error.Code);
            }

            // Type check the generated code in context of the target file
            var typeCheckResult = pipeline.TypeCheck(
                module,
                targetFile,
                isEntryPoint: false,
                maxErrors: _maxErrors,
                existingDiagnostics: _diagnostics,
                cancellationToken: cancellationToken,
                moduleRegistry: _moduleRegistry);

            foreach (var error in typeCheckResult.TypeChecker.Diagnostics.GetErrors())
            {
                _diagnostics.AddError(
                    $"In generated code from @[{genSource.GeneratorName}]: {error.Message}",
                    genSource.TriggerDecorator.LineStart, genSource.TriggerDecorator.ColumnStart,
                    code: error.Code);
            }

            _logger.LogInfo($"Integrated generated source from @[{genSource.GeneratorName}] on {genSource.TargetName}");
        }

        return !_diagnostics.HasErrors;
    }

    private string? FindFileForDeclaration(Statement declaration)
    {
        foreach (var (filePath, unit) in _projectModel!.Units)
        {
            if (unit.Ast == null)
                continue;

            foreach (var stmt in unit.Ast.Body)
            {
                if (ReferenceEquals(stmt, declaration))
                    return filePath;
            }
        }
        return null;
    }

    private static string GetDeclarationName(Statement declaration) => declaration switch
    {
        ClassDef cd => cd.Name,
        FunctionDef fd => fd.Name,
        StructDef sd => sd.Name,
        _ => "Unknown"
    };

    /// <summary>
    /// Hashes a decorator's arguments (positional + keyword) to detect when a generator's
    /// inputs change. Returns null when the decorator takes no arguments.
    /// </summary>
    private static string? ComputeDecoratorArgumentsHash(Decorator trigger)
    {
        if (trigger.Arguments.IsDefaultOrEmpty && trigger.KeywordArguments.IsDefaultOrEmpty)
        {
            return null;
        }

        var sb = new System.Text.StringBuilder();
        foreach (var arg in trigger.Arguments)
        {
            sb.Append(arg.ToString());
            sb.Append('|');
        }
        sb.Append("::");
        foreach (var kw in trigger.KeywordArguments)
        {
            sb.Append(kw.Name);
            sb.Append('=');
            sb.Append(kw.Value.ToString());
            sb.Append('|');
        }
        var hashBytes = System.Security.Cryptography.SHA256.HashData(
            System.Text.Encoding.UTF8.GetBytes(sb.ToString()));
        return Convert.ToHexStringLower(hashBytes);
    }

    /// <summary>
    /// Hashes a single declaration's AST string form to detect when a generator's
    /// target changes independently of unrelated changes in the same file.
    /// </summary>
    private static string ComputeDeclarationHash(Statement declaration)
    {
        var text = declaration.ToString() ?? string.Empty;
        var hashBytes = System.Security.Cryptography.SHA256.HashData(
            System.Text.Encoding.UTF8.GetBytes(text));
        return Convert.ToHexStringLower(hashBytes);
    }
}

internal sealed record GeneratorPartition(
    List<string> GeneratorFiles,
    List<TypeSymbol> GeneratorTypes)
{
    public bool HasGenerators => GeneratorTypes.Count > 0;
}

internal sealed record GeneratedSource(
    string Source,
    string GeneratorName,
    string TargetName,
    Decorator TriggerDecorator,
    Statement TargetDeclaration);
